/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter.
//
// A minimal hand-authored version is committed so a fresh clone typechecks and
// runs; the TanStack Router plugin regenerates it on `vite dev` / `vite build`.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as FavoritesRouteImport } from "./routes/favorites";
import { Route as TemplatesIndexRouteImport } from "./routes/templates/index";
import { Route as TemplatesIdRouteImport } from "./routes/templates/$id";
import { Route as CategorySlugRouteImport } from "./routes/category/$slug";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);

const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);

const FavoritesRoute = FavoritesRouteImport.update({
  id: "/favorites",
  path: "/favorites",
  getParentRoute: () => rootRouteImport,
} as any);

const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: "/templates/",
  path: "/templates/",
  getParentRoute: () => rootRouteImport,
} as any);

const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: "/templates/$id",
  path: "/templates/$id",
  getParentRoute: () => rootRouteImport,
} as any);

const CategorySlugRoute = CategorySlugRouteImport.update({
  id: "/category/$slug",
  path: "/category/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/favorites": {
      id: "/favorites";
      path: "/favorites";
      fullPath: "/favorites";
      preLoaderRoute: typeof FavoritesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/templates/": {
      id: "/templates/";
      path: "/templates";
      fullPath: "/templates";
      preLoaderRoute: typeof TemplatesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/templates/$id": {
      id: "/templates/$id";
      path: "/templates/$id";
      fullPath: "/templates/$id";
      preLoaderRoute: typeof TemplatesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/category/$slug": {
      id: "/category/$slug";
      path: "/category/$slug";
      fullPath: "/category/$slug";
      preLoaderRoute: typeof CategorySlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren = {
  IndexRoute,
  AuthRoute,
  ContactRoute,
  FavoritesRoute,
  TemplatesIndexRoute,
  TemplatesIdRoute,
  CategorySlugRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
